# Generated by Django 3.0.3 on 2020-02-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0007_blogpage_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
